[project]
name = "titer"
version = "1.0.0"
description = "titer is a cli for make init with question and configurations easy !"
authors = [
    { name = "yolezz" }
]
license = { text = "MIT" }
readme = "README.md"


requires-python = ">=3.13"
dependencies = [
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "tomlkit>=0.15.1",
    "typer>=0.27.2",
]

[project.scripts]
titer = "titer.cli:app"

[build-system]
requires = ["uv_build>=0.8.0,<0.9.0"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.workspace]
members = [
    "test",
]

[dependency-groups]
dev = [
    "nuitka>=4.2.1",
]
